### ISSUE TITLE
It's not possible to initialise a subset of editor features

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-bundler-rollup#1]
When reading https://github.com/ckeditor/ckeditor5/issues/260#issuecomment-234915731 I've realised that you cannot initialise editor with a subset of features that were built in. I think that you'd be able to add more features (by passing their constructors), but you won't be able to remove some.

This is bad because if you want to have two editors on one page, with a different subset of features, you'd need two bundles.

The reason why it doesn't work is that the proxy created by the bundler (see https://github.com/ckeditor/ckeditor5/blob/c248a0d1e2669a57c0f8196a5e1996be160dd1a7/dev/tasks/bundle/utils.js#L123-L139) doesn't know the names of the features. It uses constructors.

It's not a super crucial issue at the moment, but we'll need to fix it for production usage. The fix isn't obvious though because something needs to know about the `names <=> constructors`  map. We can do this in two ways:
1. Implement a feature in PluginCollection that it can be given a names map and pass this map to it through editor config (`config.pluginMap`).
2. Keep this map privately in the proxy class created by the bundler and alter the config on the fly.

I'm for the 1st solution as more features will benefit from it. I hope that it's feasible :D.

**Comment by fredck** [comment]
This is indeed a very important issue as usually, an application will have a single bundle that will be then reused for all kinds of editors inside of it.

None of your proposals is clear for me though.

**Comment by Reinmar** [comment]
> None of your proposals is clear for me though.

The problem is that something needs to know how to map feature names to feature constructors. In a dev version, if you use `PluginCollection.load()` with a string, then it tries to load the plugin from a filesystem. You can also load plugins by passing their constructors to `load()`.

The latter is used by the bundler to provide features which are concatenated with the rest of the code. But at this point we lose the plugin names. So if I try to do this:

```js
ClassicEditor.create( element, {
     features: [ 'typing', 'undo', 'paragraph' ]
} );
```

the plugin collection will try to load those 3 features from fs using System.js. That may work actually if System.js was provided, but that's the future. For now, we want to use those plugins that were bundled together with the editor. So plugin collection need to be able to understand that the strings passed to `PluginCollection.load()` represents features which were already bundled and provided in `config.pluginMap`.

**Comment by fredck** [comment]
Sorry, the problem was perfectly understood on your original issue post... I just don't understand your two proposals to solve it :)

**Comment by Reinmar** [comment]
> Sorry, the problem was perfectly understood on your original issue post... I just don't understand your two proposals to solve it :)

:D

That's the solution:

> So plugin collection need to be able to understand that the strings passed to PluginCollection.load() represents features which were already bundled and provided in config.pluginMap.

In more details – bundler's editor creator proxy must add its bundled plugin map to editor's config. That map will allow `PluginCollection` to get plugins by name without having to load them through System.js or some other module loader.

**Comment by oskarwrobel** [comment]
> That map will allow PluginCollection to get plugins by name without having to load them through > System.js or some other module loader.

Almost everyone who tried to initialize bundled editor for the first time, was passing features list to the editor configuration. Module loader doesn't know that those features are included in the bundle, and tries to load it what produces errors. It is very confusing.

**Comment by Reinmar** [comment]
This issue blocks https://github.com/ckeditor/ckeditor5-core/issues/27.

**Comment by Reinmar** [comment]
I commented on the matter of disabling and adding features in https://github.com/ckeditor/ckeditor5-core/pull/33#issuecomment-255048266.

**Comment by Reinmar** [comment]
This issue will be solved in https://github.com/ckeditor/ckeditor5-core/issues/27.
