### ISSUE TITLE
Bundler has problems with babel presets

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-dev-bundler-rollup#14]
When runing bundler following error shows: 

```
Error transforming /home/szymon/Projects/cksource/ckeditor5/ckeditor5/bundle/cMDRdX/entryfile.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead.
```

It is caused by problems with `babel-preset-es2015-rollup`. This is a standard `es2015` preset with  `modules-commonjs` plugin removed. Unfortunately its npm release is broken: https://github.com/rollup/babel-preset-es2015-rollup/issues/7 and this plugin is not removed.

Fixed version is waiting for release. For now I will add a hotfix that is using version from GitHub.

**Comment by Reinmar** [comment]
Can we revert it now? See: https://github.com/rollup/babel-preset-es2015-rollup/issues/7#issuecomment-238565650

**Comment by Reinmar** [comment]
Reverted in https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/commit/a87c6198e16e983b254d4d98ebb097e615d482d3. Apparently everything works fine.
