### ISSUE TITLE
Bundler should use builder as depencency

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-dev-bundler-rollup#18]
Bundler should have builder as npm dependency and use it as utils, not as a gulp step.

**Comment by szymonkups** [comment]
If bundler will use bundler inside, it will take care of the whole building process - maybe then it should be called a builder?

**Comment by Reinmar** [comment]
I think that I like the current setup. We've got tasks which represent separate steps and out of them you build a final one. But you do this very late, so it lets you decide how this should be performed. E.g. we talked about allowing bundling code that you prepared yourself (e.g. copied your private plugins). I think that such a setup is more flexible.

**Comment by oskarwrobel** [comment]
I've created this issue because we were talking about it and I thought it was your approach. But it could be misunderstanding :) I'm closing it.

**Comment by oskarwrobel** [comment]
But if someone thinks that it still might be worth considering, feel free to reopen :)
