### ISSUE TITLE
Ensure that it works on Windows

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-dev-bundler-rollup#20]
Described in https://github.com/ckeditor/ckeditor5/issues/228.

**Comment by szymonkups** [comment]
I've created [t/20 branch](https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/tree/t/20) that fixes tests under Windows and adds some small fixes to ensure that paths inside generated imports looks the same under each platform. 
Unfortunately there was a problem with `babel-preset-es2015-rollup`. It modifies default `babel-preset-es2015` by removing `transform-es2015-modules-commonjs` plugin. To do this it uses `modify-babel-preset` package which is not working properly under Windows. I've made PR that fixes this: https://github.com/developit/modify-babel-preset/pull/10. Let's wait for this being published on npm now.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/38.
