### ISSUE TITLE
Allow passing a path to an entry file

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-bundler-rollup#25]
Moved from https://github.com/ckeditor/ckeditor5/issues/229.

**Comment by pomek** [comment]
> We can also export a task for generating an entry file for a specified config.

At this moment, we can build the whole editor without creating the file config. If I understood correctly, we want to have a gulp task which collects the config parameters and used them to run a bundler, right?

**Comment by Reinmar** [comment]
> At this moment, we can build the whole editor without creating the file config. If I understood correctly, we want to have a gulp task which collects the config parameters and used them to run a bundler, right?

That's not correct. Currently, bundler accepts a config file and it builds an entry file for rollup based on it. What we need is a possibility to pass the entry file to the task, because sometimes you may want to create it by yourself.

**Comment by Reinmar** [comment]
Fixed by #37.
