### ISSUE TITLE
Warning - "The `this` keyword is equivalent..." - during `gulp build`

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev-bundler-rollup#27]
During Gulp task - `gulp build` - in console a warning occurs:

```
[12:12:03] Starting 'build:generate'...
The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
```

It looks like a bug somewhere in our code.

Steps to reproduce:
1. Go to main repository (`ckeditor5`),
2. Run `gulp build`.
3. Expect: the whole process won't show any warnings (and errors).

**Comment by Reinmar** [comment]
I think that Rollup could be more verbose. Would be good to check if a conf option exists for that.

**Comment by Reinmar** [comment]
After we upgraded to a new version of rollup (or some other dep) it's now clearly printed what's wrong:

```
node_modules/regenerator-runtime/runtime.js (634:295) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten. See https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined for more information
build/modules/esnext/ckeditor5/utils/lib/lodash/_root.js (25:62) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten. See https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined for more information
build/modules/esnext/ckeditor5/utils/lib/lodash/_root.js (25:72) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten. See https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined for more information
```

None of these files is our, so we can't change them. We can, however, configure rollup differently:

https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/41.
