### ISSUE TITLE
Use Babili for JS minification

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-bundler-rollup#28]
Babili (https://github.com/babel/babili) is a minifier which doesn't require transpilation to ES5. This may allow to create much smaller builds because as @oskarwrobel noticed, around 30% of code in a bundle is created by Babel.

Using Babili would need to be hidden under an option, because the bundler should default to ES5 compat build. However, this may become a pretty popular option as ES6-compat browsers take most of the market (which will be reality once Safari 10 is out and people upgrade) and Babili has also a chance to become very popular minifier as the community starts leaning towards a minifiers which don't have problems with future versions of ES (I'd need to find a link, but I saw such discussion somewhere on Uglify's tracker).

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/42.
