### ISSUE TITLE
File missing error when no config file provided

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-dev-bundler-rollup#4]
When bundler is run without `--config` option, we display:
`Bundle Error: Path to the config file is required. 'gulp bundle --config path/to/file.js'`, but after that another error is outputted to console: `Error: ENOENT: no such file or directory, stat 'bundle/ckeditor.js'`.
Bundler should stop execution after displaying the first message.

**Comment by oskarwrobel** [comment]
I think it is because of empty reject. https://github.com/ckeditor/ckeditor5-dev-bundler-rollup/blob/master/lib/index.js#L146 Looks like `runSequence` is not so clever and rejecting promise is not enough, there should be some error object passed.
